import React from "react";

const links: { label: string; href: string }[] = [
  { label: "LinkedIn", href: "https://www.linkedin.com/in/kresna-winata-649007289/" },
  { label: "Github", href: "https://github.com/whaleees" },
  { label: "HuggingFace", href: "https://huggingface.co/whaleeee" },
  { label: "Instagram", href: "https://www.instagram.com/kresnawinata1/" },
  { label: "X", href: "https://x.com/whaleeeeees_" },
];

export function AppFooter() {
  return (
    <footer className="text-center py-6 bg-neutral-100 dark:bg-neutral-900 text-xs text-neutral-600 dark:text-neutral-400">
      <p className="mb-3">
        Generated by{" "}
        <a
          className="hover:text-neutral-800 dark:hover:text-white transition"
          href="https://github.com/whaleees"
          target="_blank"
          rel="noopener noreferrer"
        >
          whaleeessss
        </a>
      </p>
      <div className="flex flex-wrap justify-center gap-4 text-sm">
        {links.map((link) => (
          <a
            key={link.label}
            href={link.href}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-neutral-800 dark:hover:text-white transition"
          >
            {link.label}
          </a>
        ))}
      </div>
    </footer>
  );
}
