"use client";

import React from "react";

const links: { label: string; href: string }[] = [
  { label: "LinkedIn", href: "https://www.linkedin.com/in/kresna-winata-649007289/" },
  { label: "Github", href: "https://github.com/whaleees" },
  { label: "HuggingFace", href: "https://huggingface.co/whaleeee" },
  { label: "Instagram", href: "https://www.instagram.com/kresnawinata1/" },
  { label: "X", href: "https://x.com/whaleeeeees_" },
];

export function AppFooter() {
  return (
    <footer className="mt-14">
      <div className="mx-auto max-w-6xl px-4">
        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#0b0b0d]/60 p-6 sm:p-8 backdrop-blur-xl">
          {/* neon hairline */}
          <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-fuchsia-500/40 via-indigo-400/40 to-emerald-400/40" />

          {/* subtle grid */}
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 opacity-[0.18]"
            style={{
              backgroundImage:
                "radial-gradient(circle at 1px 1px, rgba(255,255,255,0.10) 1px, transparent 1px)",
              backgroundSize: "14px 14px",
            }}
          />

          <div className="flex flex-col items-center gap-4 text-center">
            <p className="text-sm text-white/70">
              Generated by{" "}
              <a
                className="font-semibold text-white/90 hover:underline"
                href="https://github.com/whaleees"
                target="_blank"
                rel="noopener noreferrer"
              >
                whaleeessss
              </a>
            </p>

            <div className="flex flex-wrap items-center justify-center gap-4 text-sm">
              {links.map((link) => (
                <a
                  key={link.label}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-md border border-transparent px-3 py-1 text-white/70 transition hover:border-white/10 hover:bg-white/5 hover:text-white"
                >
                  {link.label}
                </a>
              ))}
            </div>

            <div className="text-xs text-white/40">
              © {new Date().getFullYear()} — No real funds; devnet demo only.
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
